# frozen_string_literal: true

source 'https://gems.ruby-china.com'

ruby '2.6.6'

gem 'puma', '~> 4.3'
gem 'rubyserial', '~> 0.6.0'
gem 'sinatra', '~> 2.2'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.8.1'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
